export const PWA_SHARE_READY_ACTION = 'share-ready';
export const PWA_SHARE_TARGET_SEARCH_PARAM = 'share';

export const PWA_SHARE_TARGET_UPLOAD_MEDIA_PARAM_NAME = 'file';
export const PWA_SHARE_TARGET_UPLOAD_MEDIA_ACTION = 'load-shared-media';
export const PWA_SHARE_TARGET_UPLOAD_MEDIA_ROUTE = '/upload';
export const PWA_SHARE_TARGET_UPLOAD_MEDIA_PATH = `${ PWA_SHARE_TARGET_UPLOAD_MEDIA_ROUTE }?${ PWA_SHARE_TARGET_SEARCH_PARAM }`;
