---
version: "2.7"

networks:
  proxy:
    external: true
    name: ${PROXY_NETWORK_NAME:?}

services:
  app:
    container_name: $COMPOSE_PROJECT_NAME
    pull_policy: build
    restart: always
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME:?}
    environment:
      # See https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocolheader-hostheader-and-port-header
      - HOST_HEADER=x-forwarded-host
      - PORT_HEADER=x-forwarded-port
      - PROTOCOL_HEADER=x-forwarded-proto
      # Required.
      - APP_SECRET=${APP_SECRET:?}
      - BODY_SIZE_LIMIT=${BODY_SIZE_LIMIT:?}
      - PUBLIC_MAX_FILE_SIZE=${PUBLIC_MAX_FILE_SIZE:?}
      # Optional.
      - ACCESS_KEYS
      - ORIGIN
      - WP_AUTH_ENDPOINT
      - WP_INTERNAL_URL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN:?}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"
    networks:
      - proxy
